### ISSUE TITLE
How would you listen and respond to messages?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [vivid-synth/vivid-osc#1]
I see from the readme how to send a message. Suppose, though, you also wanted to receive messages, and (say) print them to the screen as soon as they are received?

**Comment by miguel-negrao** [comment]
Most probably you would need to set up an UDP or TCP server which spits bytestrings to receive the OSC messages. Have a look [here](http://www.mchaver.com/posts/2017-06-12-haskell-network-programming-1.html) for an example. Depending on what your program is doing you probably want to put that server on a different thread as `recv`will block.

**Comment by JeffreyBenjaminBrown** [comment]
The [front page of the Hackage documentation for Vivid-OSC](https://hackage.haskell.org/package/vivid-osc) now explains how to do this. That hasn't made it onto this Github repo but I assume it'll stay on Hackage so I'll close the issue anyway.
